#!/usr/bin/env python

import sys, json

from Helper import Helper
from Config import Config

# installs = {
# 	'apache2 | nginx',
# 	'php | python | ruby',
# 	'relational db (mysql | postgre)',
# 	'nosql db (redis | mongo)',
# 	'sphinx | elastic',
# 	'git | svn',
#	'dependencies managers - composer, pear(for php)',
#	'build makers like gulp, Grunt',
# 	'framework',
#	'editors'
# }

# args = {
# 	'install',
# 	'update',
#	'configure',
#   'delete'
# }
#
# curl -i https://api.github.com/users/sephirothus - rate limit

try:
	options = {
		'-a': 'install', # action
		'-d': '1', # with dependencies
		'-c': '1' # with configuration
	}

	for arg in sys.argv:
		arg = arg.split('=')
		if (arg[0] in options): options[arg[0]] = arg[1] if len(arg) == 2 else options[arg[0]]

	confClass = Config(options['-d'])
	action = options['-a']
	helper = Helper()
	conf = {}
	fileName = 'my_config.json'

	if helper.checkFile(fileName):
		with open(fileName) as data_file:
			conf = json.load(data_file)

		queue = confClass.createQueue(conf)
	else:
		queue = confClass.createQueue(confClass.createConf())
	
	question = ["We will " + action + ":"]
	count = 1
	for el in queue:
		version = ' ' + el.attrs['version'] + ' version' if hasattr(el, 'attrs') and 'version' in el.attrs else ''
		question.append(str(count) + '. ' + el.name + version)
		count += 1

	helper.createBlock(question)
	isOk = raw_input('is it ok? ').lower()

	if isOk[0] == 'y':
		distName = helper.getDist(conf)
		for el in queue:
			helper.createBlock(helper.ucfirst(action) + ' ' + el.name)
			# checking
			check = helper.getMethod('check', el, distName)
			method = helper.getMethod(action, el, distName)
			if not method:
				print "There's no action " + action
				continue

			if action == 'install':
				if check and getattr(el, check)(): print el.name + " already installed"
				else: getattr(el, method)()
			else:
				if not check:
					print "Cannot check instance, no check method"
					continue
				if getattr(el, check)(): getattr(el, method)()
				else: print el.name + " is not installed"

			if action in ['install', 'update'] and options['-c'] == '1':
				# configuring
				if not hasattr(el, 'attrs'): el.attrs = {}
				configure = helper.getMethod('configure', el, distName)
				if configure:
					print "======= Configuring ======="
					getattr(el, configure)()

		helper.createBlock("All completed. Thanx for using pAdm:)")
	else:
		helper.createBlock("As you wish. Thanx for using pAdm:)")
	
except KeyboardInterrupt:
	print "\nBye:)"
	